services:
  - type: web
    name: sneakers-shop-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn core.wsgi:application
